apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: seblum/mlops-public:frontend_streamlit
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DB_SERVICE
            value: "backendflask"
          - name: PORT
            value: "5001"
        ports:
        - containerPort: 8501
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-node
# spec:
#   type: NodePort
#   selector:
#     app: frontend
#   ports:
#   - port: 80
#     targetPort: 8080
#     nodePort: 30000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   type: ClusterIP
#   selector:
#     app: frontend
#   ports:
#   - port: 5003
#     targetPort: 8501
