name: Docker Image CI

on:
  push:
    branches: master
    paths: Docker/**
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Put here!!


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Docker/Dockerfile
          push: true
          tags: seblum/k8straining:flask-latest
          #context: ./Docker/**
